/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-bright": "#3a3939",
        "surface-container": "#201f1f",
        "surface-variant": "#353534",
        "on-surface-variant": "#888888",
        "surface-tint": "#68dbae",
        "surface-container-high": "#2a2a2a",
        "background": "#0A0A0A",
        "on-secondary-fixed-variant": "#474646",
        "error": "#E24B4A",
        "surface": "#131313",
        "surface-container-highest": "#353534",
        "surface-container-low": "#111111",
        "outline": "#87948c",
        "on-primary-fixed-variant": "#00513a",
        "on-primary": "#003827",
        "on-secondary-fixed": "#1c1b1b",
        "primary-fixed-dim": "#68dbae",
        "inverse-on-surface": "#313030",
        "on-tertiary-fixed-variant": "#2f4f00",
        "primary-container": "#17856A",
        "secondary-fixed": "#e5e2e1",
        "secondary": "#c8c6c5",
        "on-secondary-container": "#bab8b7",
        "inverse-primary": "#006c4e",
        "error-container": "#93000a",
        "tertiary-fixed-dim": "#9dd855",
        "on-tertiary": "#1f3700",
        "on-error-container": "#ffdad6",
        "on-surface": "#F0F0F0",
        "outline-variant": "#444444",
        "secondary-fixed-dim": "#c8c6c5",
        "tertiary-fixed": "#b7f56e",
        "on-secondary": "#313030",
        "secondary-container": "#4a4949",
        "surface-container-lowest": "#0e0e0e",
        "on-tertiary-container": "#1a2f00",
        "on-tertiary-fixed": "#102000",
        "on-error": "#690005",
        "primary": "#1D9E75",
        "inverse-surface": "#e5e2e1",
        "surface-dim": "#131313",
        "on-primary-container": "#003121",
        "tertiary-container": "#69a021",
        "on-background": "#e5e2e1",
        "primary-fixed": "#86f8c9",
        "on-primary-fixed": "#002115",
        "tertiary": "#9dd855",
        "glow": "rgba(29, 158, 117, 0.15)"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        "syne": ["Archivo Black", "sans-serif"],
        "mono": ["Space Mono", "monospace"],
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "inter": ["Inter", "sans-serif"],
        "label": ["Space Grotesk", "sans-serif"]
      }
    },
  },
  plugins: [],
}
